name: Daily Math Factory

on:
  schedule:
    - cron: '0 9 * * *' # Runs everyday at 9:00 AM UTC
  workflow_dispatch: # Allows MANUAL trigger for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install System Dependencies
        # Installs ImageMagick and fixes the security policy so Python can write text
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Generate Video
        run: python main.py

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: viral-math-video
          path: |
            math_final.mp4
            metadata.txt
